name: Workflow Version
on:
  push:
    tags:
      - v0.*
      - v1.*

jobs:
  update-workflow-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          format: "${major}.${minor}.${patch}"
          bump_each_commit: false