name: Terraform tests
on:
  workflow_call:
    inputs:
      terraform_version:
        required: true
        type: string
      go_version:
        required: true
        type: string

jobs:
  go-tests:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{inputs.go_version}}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{inputs.terraform_version}}
      - name: Download Go Modules
        working-directory: test
        run: go mod tidy
      - name: Run Go Tests
        working-directory: test
        run: go test -v
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}