name: Terraform tests
on:
  workflow_call:

jobs:
  go-tests:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: autero1/action-terraform@v0.1.0
        with:
          terraform_version: 1.3.1
      - name: Download Go Modules
        working-directory: test
        run: go mod tidy
      - name: Run Go Tests
        working-directory: test
        run: go test -v
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}